name: artifact uploader

on:
  workflow_dispatch:

jobs:
  artifact-upload:
    name: "artifact-upload"
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: gitenv
        run: |
          git config --global user.name "endbugger"
          git config --global user.email "islammominul.ihemal@gmail.com"
          git config --global credential.helper store

      - name: run script
        run: |
          cd ${HOME}
          wget https://bigota.d.miui.com/V13.0.2.0.SKHMIXM/alioth_global_images_V13.0.2.0.SKHMIXM_20220314.0000.00_12.0_global_c5673c5cdb.tgz
          tar xf alioth_global_images_V13.0.2.0.SKHMIXM_20220314.0000.00_12.0_global_c5673c5cdb.tgz
          cd ali* || cd alioth_global_images_V13.0.2.0.SKHMIXM_20220314.0000.00_12.0_global_c5673c5cdb
          pt=$(find . -name partition.xml)
          cp ${pt} /tmp

      - name: upload 
        uses: actions/upload-artifact@v3
        with:
          name: partition xml
          path: /tmp/partition.xml
